services:
  database:
    container_name: postgres_dev
    image: 'postgres:17.2-alpine3.21'
    env_file:
      - ../.env.development
    ports:
      - '5432:5432'
  mailcatcher:
    container_name: mailcatcher_dev
    image: 'sj26/mailcatcher:latest'
    ports:
      - '1080:1080'
      - '1025:1025'
